<?php

namespace AppBundle\Repository;

/**
 * SpecialProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecialProductRepository extends \Doctrine\ORM\EntityRepository
{
}
