# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
      category.service:
          class: AppBundle\Service\CategoryService
          arguments: ["@doctrine"]
      product.service:
          class: AppBundle\Service\ProductService
          arguments: ["@doctrine"]
      special_product.service:
          class: AppBundle\Service\SpecialProductService
          arguments: ["@doctrine"]
      # Security
      api_key_user_provider:
              class: AppBundle\Service\Security\ApiKeyUserProvider
      apikey_authenticator:
              class:  AppBundle\Service\Security\ApiKeyAuthenticator
              public: false