# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
      category.service:
          class: AppBundle\Service\CategoryService
          arguments: ["@doctrine"]
      product.service:
          class: AppBundle\Service\ProductService
          arguments: ["@doctrine"]
      special_product.service:
          class: AppBundle\Service\SpecialProductService
          arguments: ["@doctrine"]

      # Repository
      api_user_repository:
          class: Doctrine\ORM\EntityRepository
          factory: ["@doctrine.orm.entity_manager", getRepository]
          arguments:
            - AppBundle\Entity\ApiUser

      # Security
      api_key_user_provider:
              class: AppBundle\Security\ApiKeyUserProvider
              arguments: ["@api_user_repository"]
      apikey_authenticator:
              class:  AppBundle\Security\ApiKeyAuthenticator
              public: false
              arguments: ["%api_anonymous_key%"]