AppBundle\Entity\SpecialProduct:
    exclusion_policy: ALL
    properties:
        id: { type: "integer",  expose: true }
        name: { type: "string", expose: true }
        category: { expose: true }